version: '3.2'
services:
  praat-web:
    image: maven-taln.upf.edu/praat-web:2021-11-22
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      labels:
        - "traefik.frontend.rule=Host:praat-web.${DOMAIN}"
        - "traefik.port=8080"
networks:
  traefik:
    external: true
